### ISSUE TITLE
katex rendering failed with *aligned* macro

### ISSUE THREAD

**Issue by OneForward** [amzrk2/hugo-theme-fuji#40] opened 2020-07-25 08:07 UTC
I've tried to render this [demo  equation](https://katex.org/docs/support_table.html) in markdown but the local hugo server failed to render it properly.  Normal katex equations can be rendered very nicely, though.

```latex
$$
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
$$
```

**Comment by dsrkafuu** [comment] 2020-07-25 10:24
I've tested some other demos and found the same problem. It seems that Hugo itself and its markdown parser Goldenmark were the cause. Hugo will render a `<br />` which will mess with the katex, and single `\\` will be rendered to `\` as escape characters.

You can write the katex code in one line and use `\\\\` to render as `\\` directly in markdown file.
```md
$$
\begin{matrix}
  a & b \\\\ c & d
\end{matrix}
$$
```

Or you can try updating the theme to use the new math shortcode I just committed:

**-> display style**
```md
{{< math >}}
\begin{matrix}
a & b \\
c & d
\end{matrix}
{{</ math >}}
```
**-> inline style**
```md
{{< math "inline" >}}
\begin{matrix}
a & b \\
c & d
\end{matrix}
{{</ math >}}
```

**Closed as completed** 2020-08-05 08:38 UTC
Labels: bug

**Comment by rexarski** [comment] 2020-09-08 01:20
I had the exact same issue today and `\\\\` won't make it right in the `{aligned}` environment. Tried to replace `\\` with `\cr` and it worked. It's not an elegant solution though. @OneForward
